-- GarageCherries Seed Data
-- Run AFTER schema.sql in the Supabase SQL editor

-- ─────────────────────────────────────────
-- DEALERS
-- ─────────────────────────────────────────
insert into dealers (id, slug, name, phone, email, location, state, description, specialties, since, logo, website) values
('u1',  'classic-iron-nashville',  'Classic Iron Nashville',    '(615) 555-0142', 'sales@classicironnashville.com', 'Nashville',   'TN', 'Middle Tennessee''s premier source for documented muscle cars and resto-mods. Over 30 years placing collector vehicles with serious buyers.',                                                                                                       array['Muscle Cars','Resto-Mods','GM A-Body'],             1993, null, null),
('u2',  'desert-sun-classics',     'Desert Sun Classics',       '(480) 555-0188', 'info@desertsunclassics.com',     'Scottsdale',  'AZ', 'Specializing in rust-free Southwest classics. Arizona dry climate means exceptional bodies on every car we sell.',                                                                                                                                    array['Rust-Free Classics','Convertibles','Ford & Mercury'],2001, null, null),
('u3',  'mopar-mikes',             'Mopar Mike''s',             '(704) 555-0211', 'mike@moparmikes.com',            'Charlotte',   'NC', 'The Southeast''s dedicated Mopar specialist. Chargers, Challengers, Barracudas, and Super Bees — if Chrysler built it, we know it.',                                                                                                         array['Mopar','Dodge','Plymouth','Chrysler'],               1998, null, null),
('u4',  'motor-city-muscle',       'Motor City Muscle',         '(313) 555-0177', 'sales@motorcitymuscle.com',      'Detroit',     'MI', 'Born in the Motor City, we live and breathe GM muscle. GTOs, Chevelles, 442s, and GSX cars are our bread and butter.',                                                                                                                     array['GM Muscle','Pontiac','Oldsmobile','Buick'],          1989, null, null),
('u5',  'socal-chrome',            'SoCal Chrome',              '(818) 555-0131', 'hello@socalchrome.com',          'Los Angeles', 'CA', 'Southern California classics from the golden era of American automobiles. Tri-fives, lead sleds, and custom show cars.',                                                                                                                    array['Tri-Five Chevys','Custom Cars','Show Cars'],         2005, null, null),
('u6',  'sunshine-state-classics', 'Sunshine State Classics',   '(813) 555-0199', 'info@sunshineclassics.com',      'Tampa',       'FL', 'Florida''s top destination for rare and high-value collector cars. We specialize in low-production, documented examples.',                                                                                                                  array['Rare Muscle','High-Value Collectibles','Convertibles'],2008, null, null),
('u7',  'valley-hot-rods',         'Valley Hot Rods',           '(916) 555-0144', 'builds@valleyhotrods.com',       'Sacramento',  'CA', 'Northern California''s hot rod specialists. Traditional builds, custom fabrication, and vintage tin from the pre-war era through the 1950s.',                                                                                              array['Hot Rods','Pre-War','Custom Fabrication'],           1997, null, null),
('u8',  'lone-star-pony-cars',     'Lone Star Pony Cars',       '(512) 555-0166', 'info@lonestarponycars.com',      'Austin',      'TX', 'Texas''s Mustang and Shelby authority. From early Falcons to Boss 302s and certified Shelby vehicles, we handle only the finest Ford pony cars.',                                                                                        array['Mustang','Shelby','Ford Pony Cars'],                 2003, null, null),
('u9',  'mile-high-classics',      'Mile High Classics',        '(720) 555-0188', 'sales@milehighclassics.com',     'Denver',      'CO', 'Colorado''s classic car destination. Rocky Mountain dry air keeps these cars in exceptional condition. Station wagons, trucks, and two-doors.',                                                                                            array['Station Wagons','Tri-Five','Classic Trucks'],        2010, null, null),
('u10', 'windy-city-vettes',       'Windy City Vettes',         '(312) 555-0222', 'info@windycityvettes.com',       'Chicago',     'IL', 'The Midwest''s Corvette specialists since 1991. Every year from C1 through C5, with documentation, NCRS judging, and concours restorations.',                                                                                           array['Corvette','C1','C2','C3'],                          1991, null, null),
('u11', 'pacific-nw-hot-rods',     'Pacific NW Hot Rods',       '(503) 555-0155', 'builds@pacificnwhotrods.com',    'Portland',    'OR', 'Pacific Northwest custom builders specializing in 1930s and 1940s Ford hot rods. Traditional builds using period-correct parts and techniques.',                                                                                          array['1930s Ford','1940s Ford','Traditional Hot Rods'],    2000, null, null),
('u12', 'peach-state-muscle',      'Peach State Muscle',        '(404) 555-0177', 'info@peachstatemuscle.com',      'Atlanta',     'GA', 'The Southeast''s go-to source for documented GM muscle cars. Chevelles, El Caminos, Monte Carlos, and Nova SS models are our specialty.',                                                                                               array['Chevelle','El Camino','Nova SS','GM A-Body'],        2006, null, null),
('u13', 'fastlane-cars',           'Fast Lane Classic Cars',    '(314) 555-0100', 'sales@fastlanecars.com',         'St. Charles', 'MO',
  E'Founded in 1994, we are a family-owned classic and collector car dealership located in St. Charles, Missouri. Our campus has three huge showrooms filled with over 180 high-quality cars, trucks, and motorcycles. We are the Midwest''s largest Backdraft dealer, specializing in custom-built Cobra replicas. We have a state-of-the-art service facility, a restoration shop, and an auto detail facility. Our buildings feature automobile art, memorabilia, and antiques curated from around the world, and our gift shop has something for every auto enthusiast. There is something for everyone at Fast Lane Classic Cars!\n\nWe work every day to earn the reputation our business was founded on. To provide the best quality cars, trucks, and motorcycles and to be as honest and clear with every customer as possible. We are committed to make sure buying a Fast Lane car is the only way to invest in a vintage vehicle!',
  array['Classic Cars','Muscle Cars','Cobra Replicas','Motorcycles','Trucks'], 1994, '/dealers/fastlane-logo.svg', 'https://www.fastlanecars.com')
on conflict (id) do nothing;

-- ─────────────────────────────────────────
-- CARS
-- ─────────────────────────────────────────
insert into cars (id, slug, title, year, make, model, price, mileage, location, state, condition, body_style, transmission, engine, color, images, description, seller_id, seller_name, seller_phone, featured, listed_at) values
('1',  '1967-chevrolet-camaro-ss',       '1967 Chevrolet Camaro SS',       1967, 'Chevrolet', 'Camaro',      89500,  42100, 'Nashville',   'TN', 'Excellent', 'Coupe',         'Manual',    '396 V8',              'Rally Green',                  array['https://images.unsplash.com/photo-1555353540-64580b51c258?w=800&q=80','https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80'], 'Numbers-matching 1967 Camaro SS 396. Frame-off restoration completed in 2021. Correct Muncie 4-speed, original trim tags present. Show quality throughout.', 'u1',  'Classic Iron Nashville',    '(615) 555-0142', true,  '2025-05-10'),
('2',  '1957-ford-thunderbird',          '1957 Ford Thunderbird',           1957, 'Ford',       'Thunderbird', 64900,  58320, 'Scottsdale',  'AZ', 'Excellent', 'Convertible',   'Automatic', '312 V8',              'Flame Red',                    array['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80'],                                                                         'Stunning 1957 T-Bird with both hard and soft tops. Arizona car, rust-free body. Recently serviced, drives beautifully.',                                  'u2',  'Desert Sun Classics',       '(480) 555-0188', true,  '2025-05-12'),
('3',  '1969-dodge-charger-rt',          '1969 Dodge Charger R/T',         1969, 'Dodge',      'Charger',     112000, 31450, 'Charlotte',   'NC', 'Excellent', 'Hardtop',       'Automatic', '440 Magnum V8',       'Plum Crazy Purple',             array['https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80'],                                                                         'Broadcast sheet documented 1969 Charger R/T 440. TorqueFlite automatic. Correct Plum Crazy paint. Numbers match on block and heads.',                   'u3',  'Mopar Mike''s',             '(704) 555-0211', true,  '2025-05-08'),
('4',  '1964-pontiac-gto',               '1964 Pontiac GTO',               1964, 'Pontiac',    'GTO',         78000,  67200, 'Detroit',     'MI', 'Good',      'Coupe',         'Manual',    '389 Tri-Power V8',    'Grenadier Red',                 array['https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80'],                                                                         'First-year GTO with rare Tri-Power setup. Solid Michigan car with documented history. Recent brake and cooling system service.',                          'u4',  'Motor City Muscle',         '(313) 555-0177', false, '2025-05-15'),
('5',  '1955-chevrolet-bel-air',         '1955 Chevrolet Bel Air',         1955, 'Chevrolet',  'Bel Air',     52500,  84300, 'Los Angeles', 'CA', 'Good',      'Hardtop',       'Automatic', '265 V8',              'Harvest Gold / India Ivory',    array['https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80'],                                                                         'Classic two-tone 1955 Bel Air in iconic colors. PowerGlide automatic. Solid California body, no rust. Great daily driver or show car.',                  'u5',  'SoCal Chrome',              '(818) 555-0131', false, '2025-05-18'),
('6',  '1970-plymouth-barracuda',        '1970 Plymouth Barracuda',        1970, 'Plymouth',   'Barracuda',   95000,  22800, 'Tampa',       'FL', 'Excellent', 'Convertible',   'Manual',    '440 Six-Pack V8',     'Vitamin C Orange',              array['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80'],                                                                         '1970 Barracuda convertible with the rare 440 Six-Pack. One of 9 known examples with this combination. Full restoration, show winner.',                   'u6',  'Sunshine State Classics',   '(813) 555-0199', true,  '2025-05-06'),
('7',  '1932-ford-highboy-roadster',     '1932 Ford Highboy Roadster',     1932, 'Ford',       'Model B',     47500,  5200,  'Sacramento',  'CA', 'Excellent', 'Roadster',      'Manual',    '327 Small Block V8',  'Satin Black',                   array['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80'],                                                                         E'Traditional styled \'32 Ford highboy hot rod. Steel body, 327 SBC, polished Halibrand knockoffs. AMBR contender quality build.',                       'u7',  'Valley Hot Rods',           '(916) 555-0144', false, '2025-05-20'),
('8',  '1966-shelby-gt350',              '1966 Shelby GT350',              1966, 'Ford',       'Mustang',     185000, 19400, 'Austin',      'TX', 'Excellent', 'Fastback',      'Manual',    '289 Hi-Po K-Code V8', 'Wimbledon White',               array['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800&q=80'],                                                                         'Authenticated 1966 Shelby GT350 with Shelby American Automobile Club certification. All numbers match, original interior. Investment grade.',             'u8',  'Lone Star Pony Cars',       '(512) 555-0166', true,  '2025-05-02'),
('9',  '1957-chevrolet-nomad',           '1957 Chevrolet Nomad',           1957, 'Chevrolet',  'Nomad',       71000,  61700, 'Denver',      'CO', 'Good',      'Station Wagon', 'Automatic', '283 V8',              'Laurel Green / India Ivory',    array['https://images.unsplash.com/photo-1609629048082-ba5cb8c7b4da?w=800&q=80'],                                                                         'Highly sought-after 1957 Nomad wagon. One of the rarest body styles from the tri-five era. Solid car with professional paint.',                          'u9',  'Mile High Classics',        '(720) 555-0188', false, '2025-05-22'),
('10', '1969-chevrolet-corvette-stingray','1969 Chevrolet Corvette Stingray',1969,'Chevrolet', 'Corvette',    88000,  44600, 'Chicago',     'IL', 'Excellent', 'Coupe',         'Manual',    '427 L71 V8',          'Can-Am White',                  array['https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&q=80'],                                                                         'Numbers-matching 1969 Stingray with the rare 427/435hp L71 engine. 4-speed close-ratio, side pipes. Concours-level restoration.',                       'u10', 'Windy City Vettes',         '(312) 555-0222', false, '2025-05-14'),
('11', '1940-ford-deluxe-coupe',         '1940 Ford Deluxe Coupe',         1940, 'Ford',       'Deluxe',      38500,  12000, 'Portland',    'OR', 'Good',      'Coupe',         'Manual',    '350 Small Block V8',  'Dark Blue Metallic',            array['https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=800&q=80'],                                                                         'Sweet 1940 Ford coupe with a tuck-and-roll interior and modern drivetrain. Reliable, fun, and turns heads everywhere.',                                   'u11', 'Pacific NW Hot Rods',       '(503) 555-0155', false, '2025-05-25'),
('12', '1971-chevelle-ss-454',           '1971 Chevelle SS 454',           1971, 'Chevrolet',  'Chevelle',    67500,  53200, 'Atlanta',     'GA', 'Good',      'Hardtop',       'Automatic', '454 LS5 V8',          'Cranberry Red',                 array['https://images.unsplash.com/photo-1526726538690-5cbf956ae2fd?w=800&q=80'],                                                                         'Documented SS 454 Chevelle. Turbo-Hydramatic 400, correct Cowl-Induction hood. Recent frame-off, driver-quality paint.',                                 'u12', 'Peach State Muscle',        '(404) 555-0177', false, '2025-05-17'),
('13', '1967-plymouth-gtx-hemi',         '1967 Plymouth GTX Hemi',         1967, 'Plymouth',   'GTX',         0,      99606, 'St. Charles', 'MO', 'Excellent', 'Coupe',         'Manual',    '426 Hemi V8',         'Bright Red',
  array['/cars/1967 Plymouth GTX/1967-plymouth-gtx-hemi.jpg','/cars/1967 Plymouth GTX/1967-plymouth-gtx-hemi-engine.jpg','/cars/1967 Plymouth GTX/1967-plymouth-gtx-hemi-interior.jpg'],
  '1967 Plymouth GTX with 426 Hemi V8, 4-speed manual, Sure-Grip rear. Bright Red with red vinyl bucket interior. Power steering, power front disc brakes.',
  'u13', 'Fast Lane Classic Cars', '(314) 555-0100', true, '2026-06-14')
on conflict (id) do nothing;

-- Extra fields for GTX
update cars set
  headline            = 'THE GENTLEMAN''S MUSCLE CAR WITH RAW HEMI POWER',
  hobby_segment       = 'Muscle Car',
  doors               = 2,
  interior_color      = 'Bright Red',
  seat_material       = 'Vinyl',
  seating_type        = 'Bucket',
  rear_wheel_spec     = 'Special Factory',
  options             = array['Power Steering','Power Front Disc Brakes','8 Track Player'],
  description_paragraphs = array[
    'This 1967 Plymouth GTX is more than just a muscle car, it''s a statement. Known as "The Gentleman''s Muscle Car," this Bright Red beauty packs the perfect mix of style, sophistication, and unrelenting power. Under the hood is the legendary 426 Hemi V8, mated to a 4-speed manual transmission and a Sure-Grip rear differential with 3.55 gears. If you''ve been searching for a 1967 GTX Hemi that delivers street presence and brute performance, this is it.',
    'The exterior is finished in a brilliant Bright Red, accented by dual hood scoops and matching red steel wheels wrapped in classic redline tires. Dog dish hubcaps complete the no-nonsense, factory-correct look that made the ''67 GTX a standout from the start. Inside, the red vinyl bucket seat interior is as clean and commanding as the exterior, featuring a center console and a period-correct Mopar 8-track player to keep the vintage vibes alive.',
    'Power steering and power front disc brakes make this 1967 GTX for sale just as enjoyable to drive as it is to look at. From its unmistakable silhouette to the thunderous sound of the 426 Hemi, this ''67 Plymouth GTX for sale is a dream car for collectors and enthusiasts alike.',
    'Opportunities to own a true 1967 Plymouth GTX Hemi don''t come around often, especially in this condition. If you''re looking to buy a ''67 GTX Hemi that has pedigree, performance, and presence, this one''s ready to take its place in your garage!'
  ]
where id = '13';
